version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: MyPassword$
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_TRANSACTION_XA_ENABLED: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9091:8080"
    command:
      - start-dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.34
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: MyPassword$
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  ms-transaction:
    image: mysql:8.0.34
    container_name: ms-transaction
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transaction_db
      MYSQL_USER: user-transaction
      MYSQL_PASSWORD: transaction-pass
    ports:
      - "3310:3306"
    volumes:
      - db_transaction:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db_data:
  db_transaction:




