server:
  port: 8082
  context-path: /user/

spring:
  application:
    name: ms-user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/triwal-realm-dev
          jwk-set-uri: http://localhost:9090/realms/triwal-realm-dev/protocol/openid-connect/certs

# ESTO ME PERMITE ENVIAR EL LINK AL CORREO PARA HABILITAR NUEVAMENTE LA CUENTA
  mail:
    host: smtp.gmail.com
    port: 587
    username: triwalwebapp@gmail.com
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwtConverter:
  auth:
    converter:
      resource-id: triwal-app
      main-attr: preferred_username


logging:
  level:
    root: info